name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *'   # Her saat başı çalışır
  workflow_dispatch:       # İstersen elle de çalıştırabilirsin

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync upstream
        run: |
          git remote add upstream https://github.com/malibayram/single_letter_transformers.git
          git fetch upstream
          git checkout main
          git merge upstream/main --no-edit
          git push origin main
