name: Sync Fork

on:
  schedule:
    - cron: "0 * * * *"   # Her saat çalışır
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync fork
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "malibayram/single_letter_transformers"
          source_branch: "main"
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
